/*
 * CLAOS 3D Engine — Fixed-Point Math Library
 *
 * All 3D math uses 16.16 fixed-point. No floating point in the render loop.
 * Trig tables are pre-generated by tools/gen_trig.py.
 */

#ifndef CLAOS_FIXED_H
#define CLAOS_FIXED_H

#include "types.h"

typedef int32_t  fixed_t;
typedef int64_t  fixed64_t;  /* intermediate multiply results */

#define FP_SHIFT      16
#define FP_ONE        (1 << FP_SHIFT)         /* 1.0 = 65536 */
#define FP_HALF       (1 << (FP_SHIFT - 1))   /* 0.5 = 32768 */

#define INT_TO_FP(x)  ((fixed_t)(x) << FP_SHIFT)
#define FP_TO_INT(x)  ((x) >> FP_SHIFT)
#define FLOAT_TO_FP(x) ((fixed_t)((x) * FP_ONE))  /* compile-time only */

#define FP_MUL(a, b)  ((fixed_t)(((fixed64_t)(a) * (b)) >> FP_SHIFT))
#define FP_DIV(a, b)  ((fixed_t)(((fixed64_t)(a) << FP_SHIFT) / (b)))

/* Absolute value */
#define FP_ABS(x)     ((x) < 0 ? -(x) : (x))

/* Trig lookup tables (4096 entries = 360 degrees) */
#define ANGLE_360     4096
#define ANGLE_180     2048
#define ANGLE_90      1024
#define ANGLE_45      512
#define ANGLE_MASK    4095

extern const fixed_t sin_table[ANGLE_360];
extern const fixed_t cos_table[ANGLE_360];
extern const fixed_t tan_table[ANGLE_360];

static inline fixed_t fp_sin(int angle) { return sin_table[angle & ANGLE_MASK]; }
static inline fixed_t fp_cos(int angle) { return cos_table[angle & ANGLE_MASK]; }
static inline fixed_t fp_tan(int angle) { return tan_table[angle & ANGLE_MASK]; }

#endif /* CLAOS_FIXED_H */
