#!/usr/bin/env python3
"""
Generate fixed-point trig lookup tables for CLAOS 3D engine.
Outputs engine3d/trig_tables.c with sin/cos/tan as const arrays.
"""
import math
import os

ANGLE_COUNT = 4096
FP_SHIFT = 16
FP_ONE = 1 << FP_SHIFT
FP_MAX = 0x7FFFFFFF   # max int32_t

def to_fixed(f):
    """Convert float to 16.16 fixed-point, clamped to int32_t range."""
    v = int(round(f * FP_ONE))
    if v > FP_MAX:
        v = FP_MAX
    elif v < -FP_MAX:
        v = -FP_MAX
    return v

def main():
    sin_table = []
    cos_table = []
    tan_table = []

    for i in range(ANGLE_COUNT):
        angle = i * 2.0 * math.pi / ANGLE_COUNT
        s = math.sin(angle)
        c = math.cos(angle)

        sin_table.append(to_fixed(s))
        cos_table.append(to_fixed(c))

        # tan: clamp near +/-90 degrees to avoid overflow
        if abs(c) < 1e-6:
            tan_table.append(FP_MAX if s >= 0 else -FP_MAX)
        else:
            t = s / c
            tan_table.append(to_fixed(t))

    # Output C file
    out_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "engine3d")
    out_path = os.path.join(out_dir, "trig_tables.c")

    with open(out_path, "w") as f:
        f.write("/*\n")
        f.write(" * CLAOS 3D Engine — Pre-generated trig lookup tables\n")
        f.write(" * Generated by tools/gen_trig.py — DO NOT EDIT\n")
        f.write(" *\n")
        f.write(" * 4096 entries = 360 degrees, 16.16 fixed-point\n")
        f.write(" */\n\n")
        f.write('#include "fixed.h"\n\n')

        def write_table(name, table):
            f.write(f"const fixed_t {name}[ANGLE_360] = {{\n")
            for i in range(0, len(table), 8):
                chunk = table[i:i+8]
                f.write("    " + ", ".join(str(v) for v in chunk))
                if i + 8 < len(table):
                    f.write(",")
                f.write("\n")
            f.write("};\n\n")

        write_table("sin_table", sin_table)
        write_table("cos_table", cos_table)
        write_table("tan_table", tan_table)

    print(f"Generated {out_path}")
    print(f"  sin_table: {len(sin_table)} entries")
    print(f"  cos_table: {len(cos_table)} entries")
    print(f"  tan_table: {len(tan_table)} entries")

if __name__ == "__main__":
    main()
